### ISSUE TITLE
CoinInfo map() function error

### ISSUE THREAD

**Issue by Nyamgavaa** [piyush-eon/react-crypto-tracker#2]
thanks for making great content

I face really confusing error. Could you suggest me how to fix this error.

The error occured adding this section of code into CoinInfo.js

<Line data={{
              labels: historicData.map((coin) => {}),
            }}
            />

![image](https://user-images.githubusercontent.com/40618924/154798195-b967f970-cc9a-40af-a381-d8ac665c0606.png)

MY CoinInfo.js 

import axios from 'axios';
import  { useEffect, useState } from 'react';
import {CryptoState} from  "../CryptoContext";
import { HistoricalChart } from '../config/api';
import { CircularProgress,
         createTheme,
         makeStyles,
         ThemeProvider,
   } from '@material-ui/core';
//import {Line} from "react-chartjs-2"
import {Line} from "react-chartjs-2"

// import axios from "axios";
// import { useEffect, useState } from "react";
// import { HistoricalChart } from "../config/api";
// import { Line } from "react-chartjs-2";
// import {
//   CircularProgress,
//   createTheme,
//   makeStyles,
//   ThemeProvider,
// } from "@material-ui/core";
// import SelectButton from "./SelectButton";
// import { chartDays } from "../config/data";
// import { CryptoState } from "../CryptoContext";

const CoinInfo = ({ coin }) => {
const [historicData, setHistoricData] = useState()
const [days, setDays]= useState(1)

const {currency} = CryptoState()

const fetchHistoricData = async () => {
  const { data } = await axios.get(HistoricalChart(coin.id, days, currency));

  setHistoricData(data.prices)
}

console.log("Түүхэн өгөгдөл", historicData)

useEffect(() => {
  fetchHistoricData();
},[currency, days]);

const darkTheme = createTheme({
  palette: {
    primary: {
      main: "#fff",
    },
    type: "dark"
  },

})

const useStyles = makeStyles((theme) => ({
  container: {
    width: "75%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 25,
    padding: 40,
    [theme.breakpoints.down("md")]: {
      width: "100%",
      marginTop: 0,
      padding: 20,
      paddingTop: 0,
    },
  },
}));

const classes = useStyles()
  return (

    <ThemeProvider theme={darkTheme}>
      <div className={classes.container}>
        
        {!historicData ? (
            <CircularProgress
            style={{color: "gold"}}
            size={250}
            thickness={1}
            />
          ): (<>
              <Line data={{
              labels: historicData.map(() => {}),
            }}
            />
          </>)
          
        }

        {/* buttons */}

      </div>
    </ThemeProvider>
  );
};

export default CoinInfo;
Thank you very much

**Comment by pranjalshikhar** [comment]
Please uninstall react-chartjs-2 and chart.js. 
`npm uninstall chart.js react-chartjs-2`
Add add,
`npm i chart.js@3.0.0 react-chartjs-2@3.0.0`

**Comment by Nyamgavaa** [comment]
i fix this issue adding. Thank yo very much

import { Chart, registerables } from 'chart.js';
Chart.register(...registerables);

**Comment by Nyamgavaa** [comment]
> Please uninstall react-chartjs-2 and chart.js. `npm uninstall chart.js react-chartjs-2` Add add, `npm i chart.js@3.0.0 react-chartjs-2@3.0.0`

Thank you very much answering my rookie question

After 10 hour researching I fix this issue .
